// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgChat.proto

package org.jyg.gameserver.test.proto;

public final class MsgChatOuterClass {
  private MsgChatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jyg_gameserver_core_proto_MsgChat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jyg_gameserver_core_proto_MsgChat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgChat.proto\022\035org.jyg.gameserver.core" +
      ".proto\"&\n\007MsgChat\022\n\n\002id\030\001 \001(\005\022\017\n\007content" +
      "\030\002 \001(\tB!\n\035org.jyg.gameserver.test.protoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_jyg_gameserver_core_proto_MsgChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jyg_gameserver_core_proto_MsgChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jyg_gameserver_core_proto_MsgChat_descriptor,
        new java.lang.String[] { "Id", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
