// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgChat.proto

package org.jyg.gameserver.test.proto;

public interface MsgChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.core.proto.MsgChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
