// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MsgChat.proto
// Protobuf Java Version: 4.28.0

package org.jyg.gameserver.proto;

public interface MsgChatReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.proto.MsgChatReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string account = 1;</code>
   * @return The account.
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 1;</code>
   * @return The bytes for account.
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
