// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MsgChat.proto
// Protobuf Java Version: 4.28.0

package org.jyg.gameserver.proto;

public final class MsgChat {
  private MsgChat() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      MsgChat.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jyg_gameserver_proto_MsgChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jyg_gameserver_proto_MsgChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jyg_gameserver_proto_MsgChatReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jyg_gameserver_proto_MsgChatReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgChat.proto\022\030org.jyg.gameserver.prot" +
      "o\"!\n\016MsgChatRequest\022\017\n\007content\030\001 \001(\t\"0\n\014" +
      "MsgChatReply\022\017\n\007account\030\001 \001(\t\022\017\n\007content" +
      "\030\002 \001(\tB\034\n\030org.jyg.gameserver.protoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_jyg_gameserver_proto_MsgChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jyg_gameserver_proto_MsgChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_jyg_gameserver_proto_MsgChatRequest_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_org_jyg_gameserver_proto_MsgChatReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_jyg_gameserver_proto_MsgChatReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_jyg_gameserver_proto_MsgChatReply_descriptor,
        new java.lang.String[] { "Account", "Content", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
