// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgLogin.proto

package org.jyg.gameserver.proto;

public final class MsgLogin {
  private MsgLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jyg_gameserver_proto_MsgLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jyg_gameserver_proto_MsgLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jyg_gameserver_proto_MsgLoginReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jyg_gameserver_proto_MsgLoginReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MsgLogin.proto\022\030org.jyg.gameserver.pro" +
      "to\"$\n\017MsgLoginRequest\022\021\n\tplayerUid\030\001 \001(\003" +
      "\"1\n\rMsgLoginReply\022\021\n\tplayerUid\030\001 \001(\003\022\r\n\005" +
      "token\030\002 \001(\tB\034\n\030org.jyg.gameserver.protoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_jyg_gameserver_proto_MsgLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jyg_gameserver_proto_MsgLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jyg_gameserver_proto_MsgLoginRequest_descriptor,
        new java.lang.String[] { "PlayerUid", });
    internal_static_org_jyg_gameserver_proto_MsgLoginReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_jyg_gameserver_proto_MsgLoginReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jyg_gameserver_proto_MsgLoginReply_descriptor,
        new java.lang.String[] { "PlayerUid", "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
