// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgLogin.proto

package org.jyg.gameserver.proto;

public interface MsgLoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.proto.MsgLoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 playerUid = 1;</code>
   */
  long getPlayerUid();
}
