// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MsgLogin.proto
// Protobuf Java Version: 4.28.0

package org.jyg.gameserver.proto;

public interface MsgLoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.proto.MsgLoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string account = 1;</code>
   * @return The account.
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 1;</code>
   * @return The bytes for account.
   */
  com.google.protobuf.ByteString
      getAccountBytes();
}
