// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgLogin.proto

package org.jyg.gameserver.proto;

public interface MsgLoginReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.proto.MsgLoginReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 playerUid = 1;</code>
   */
  long getPlayerUid();

  /**
   * <code>string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
