// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MsgLogin.proto
// Protobuf Java Version: 4.28.0

package org.jyg.gameserver.proto;

public final class MsgLogin {
  private MsgLogin() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      MsgLogin.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jyg_gameserver_proto_MsgLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jyg_gameserver_proto_MsgLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jyg_gameserver_proto_MsgLoginReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jyg_gameserver_proto_MsgLoginReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MsgLogin.proto\022\030org.jyg.gameserver.pro" +
      "to\"\"\n\017MsgLoginRequest\022\017\n\007account\030\001 \001(\t\"/" +
      "\n\rMsgLoginReply\022\017\n\007account\030\001 \001(\t\022\r\n\005toke" +
      "n\030\002 \001(\tB\034\n\030org.jyg.gameserver.protoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_jyg_gameserver_proto_MsgLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jyg_gameserver_proto_MsgLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_jyg_gameserver_proto_MsgLoginRequest_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_org_jyg_gameserver_proto_MsgLoginReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_jyg_gameserver_proto_MsgLoginReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_jyg_gameserver_proto_MsgLoginReply_descriptor,
        new java.lang.String[] { "Account", "Token", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
