// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgPing.proto

package org.jyg.gameserver.proto;

public interface MsgPingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.proto.MsgPing)
    com.google.protobuf.MessageOrBuilder {
}
