// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MsgPing.proto
// Protobuf Java Version: 4.28.0

package org.jyg.gameserver.proto;

public interface MsgPingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.proto.MsgPing)
    com.google.protobuf.MessageOrBuilder {
}
