// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BytesMsg.proto

package org.jyg.gameserver.core.proto;

public interface BytesMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.core.proto.BytesMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 msgId = 1;</code>
   */
  int getMsgId();

  /**
   * <code>int64 sessionId = 2;</code>
   */
  long getSessionId();

  /**
   * <code>bytes msgData = 3;</code>
   */
  com.google.protobuf.ByteString getMsgData();
}
