// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgBytes.proto

package org.jyg.gameserver.core.proto;

public interface MsgBytesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jyg.gameserver.core.proto.MsgBytes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>bytes byteData = 2;</code>
   */
  com.google.protobuf.ByteString getByteData();
}
