/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.jyg.proto.p_sm_scene_request_ping');
goog.provide('proto.com.jyg.proto.p_sm_scene_request_ping.Car');
goog.provide('proto.com.jyg.proto.p_sm_scene_request_ping.CarType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.jyg.proto.p_sm_scene_request_ping = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.jyg.proto.p_sm_scene_request_ping.repeatedFields_, null);
};
goog.inherits(proto.com.jyg.proto.p_sm_scene_request_ping, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.jyg.proto.p_sm_scene_request_ping.displayName = 'proto.com.jyg.proto.p_sm_scene_request_ping';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.jyg.proto.p_sm_scene_request_ping.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.toObject = function(opt_includeInstance) {
  return proto.com.jyg.proto.p_sm_scene_request_ping.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.jyg.proto.p_sm_scene_request_ping} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jyg.proto.p_sm_scene_request_ping.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    email: jspb.Message.getFieldWithDefault(msg, 3, ""),
    carsList: jspb.Message.toObjectList(msg.getCarsList(),
    proto.com.jyg.proto.p_sm_scene_request_ping.Car.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.jyg.proto.p_sm_scene_request_ping}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.jyg.proto.p_sm_scene_request_ping;
  return proto.com.jyg.proto.p_sm_scene_request_ping.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.jyg.proto.p_sm_scene_request_ping} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.jyg.proto.p_sm_scene_request_ping}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 4:
      var value = new proto.com.jyg.proto.p_sm_scene_request_ping.Car;
      reader.readMessage(value,proto.com.jyg.proto.p_sm_scene_request_ping.Car.deserializeBinaryFromReader);
      msg.addCars(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.jyg.proto.p_sm_scene_request_ping.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.jyg.proto.p_sm_scene_request_ping} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jyg.proto.p_sm_scene_request_ping.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCarsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.com.jyg.proto.p_sm_scene_request_ping.Car.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.CarType = {
  AUDI: 0,
  BENZ: 1,
  LAMBORGHINI: 2,
  DASAUTO: 3
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.jyg.proto.p_sm_scene_request_ping.Car, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.jyg.proto.p_sm_scene_request_ping.Car.displayName = 'proto.com.jyg.proto.p_sm_scene_request_ping.Car';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.prototype.toObject = function(opt_includeInstance) {
  return proto.com.jyg.proto.p_sm_scene_request_ping.Car.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.jyg.proto.p_sm_scene_request_ping.Car} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.jyg.proto.p_sm_scene_request_ping.Car}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.jyg.proto.p_sm_scene_request_ping.Car;
  return proto.com.jyg.proto.p_sm_scene_request_ping.Car.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.jyg.proto.p_sm_scene_request_ping.Car} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.jyg.proto.p_sm_scene_request_ping.Car}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {!proto.com.jyg.proto.p_sm_scene_request_ping.CarType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.jyg.proto.p_sm_scene_request_ping.Car.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.jyg.proto.p_sm_scene_request_ping.Car} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional CarType type = 2;
 * @return {!proto.com.jyg.proto.p_sm_scene_request_ping.CarType}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.prototype.getType = function() {
  return /** @type {!proto.com.jyg.proto.p_sm_scene_request_ping.CarType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.com.jyg.proto.p_sm_scene_request_ping.CarType} value */
proto.com.jyg.proto.p_sm_scene_request_ping.Car.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string email = 3;
 * @return {string}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated Car cars = 4;
 * @return {!Array.<!proto.com.jyg.proto.p_sm_scene_request_ping.Car>}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.getCarsList = function() {
  return /** @type{!Array.<!proto.com.jyg.proto.p_sm_scene_request_ping.Car>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.jyg.proto.p_sm_scene_request_ping.Car, 4));
};


/** @param {!Array.<!proto.com.jyg.proto.p_sm_scene_request_ping.Car>} value */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.setCarsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.com.jyg.proto.p_sm_scene_request_ping.Car=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.jyg.proto.p_sm_scene_request_ping.Car}
 */
proto.com.jyg.proto.p_sm_scene_request_ping.prototype.addCars = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.com.jyg.proto.p_sm_scene_request_ping.Car, opt_index);
};


proto.com.jyg.proto.p_sm_scene_request_ping.prototype.clearCarsList = function() {
  this.setCarsList([]);
};


