// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_auth_sm.proto

package com.jyg.proto;

public final class p_auth_sm {
  private p_auth_sm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface p_auth_sm_register_roleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jyg.proto.p_auth_sm_register_role)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.jyg.proto.p_auth_sm_register_role}
   */
  public  static final class p_auth_sm_register_role extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jyg.proto.p_auth_sm_register_role)
      p_auth_sm_register_roleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_auth_sm_register_role.newBuilder() to construct.
    private p_auth_sm_register_role(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_auth_sm_register_role() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_auth_sm_register_role(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_register_role_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_register_role_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jyg.proto.p_auth_sm.p_auth_sm_register_role.class, com.jyg.proto.p_auth_sm.p_auth_sm_register_role.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jyg.proto.p_auth_sm.p_auth_sm_register_role)) {
        return super.equals(obj);
      }
      com.jyg.proto.p_auth_sm.p_auth_sm_register_role other = (com.jyg.proto.p_auth_sm.p_auth_sm_register_role) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jyg.proto.p_auth_sm.p_auth_sm_register_role prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jyg.proto.p_auth_sm_register_role}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jyg.proto.p_auth_sm_register_role)
        com.jyg.proto.p_auth_sm.p_auth_sm_register_roleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_register_role_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_register_role_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jyg.proto.p_auth_sm.p_auth_sm_register_role.class, com.jyg.proto.p_auth_sm.p_auth_sm_register_role.Builder.class);
      }

      // Construct using com.jyg.proto.p_auth_sm.p_auth_sm_register_role.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_register_role_descriptor;
      }

      public com.jyg.proto.p_auth_sm.p_auth_sm_register_role getDefaultInstanceForType() {
        return com.jyg.proto.p_auth_sm.p_auth_sm_register_role.getDefaultInstance();
      }

      public com.jyg.proto.p_auth_sm.p_auth_sm_register_role build() {
        com.jyg.proto.p_auth_sm.p_auth_sm_register_role result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jyg.proto.p_auth_sm.p_auth_sm_register_role buildPartial() {
        com.jyg.proto.p_auth_sm.p_auth_sm_register_role result = new com.jyg.proto.p_auth_sm.p_auth_sm_register_role(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jyg.proto.p_auth_sm.p_auth_sm_register_role) {
          return mergeFrom((com.jyg.proto.p_auth_sm.p_auth_sm_register_role)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jyg.proto.p_auth_sm.p_auth_sm_register_role other) {
        if (other == com.jyg.proto.p_auth_sm.p_auth_sm_register_role.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jyg.proto.p_auth_sm.p_auth_sm_register_role parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jyg.proto.p_auth_sm.p_auth_sm_register_role) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jyg.proto.p_auth_sm_register_role)
    }

    // @@protoc_insertion_point(class_scope:com.jyg.proto.p_auth_sm_register_role)
    private static final com.jyg.proto.p_auth_sm.p_auth_sm_register_role DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jyg.proto.p_auth_sm.p_auth_sm_register_role();
    }

    public static com.jyg.proto.p_auth_sm.p_auth_sm_register_role getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_auth_sm_register_role>
        PARSER = new com.google.protobuf.AbstractParser<p_auth_sm_register_role>() {
      public p_auth_sm_register_role parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new p_auth_sm_register_role(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_auth_sm_register_role> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_auth_sm_register_role> getParserForType() {
      return PARSER;
    }

    public com.jyg.proto.p_auth_sm.p_auth_sm_register_role getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface p_sm_auth_register_role_successOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jyg.proto.p_sm_auth_register_role_success)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.jyg.proto.p_sm_auth_register_role_success}
   */
  public  static final class p_sm_auth_register_role_success extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jyg.proto.p_sm_auth_register_role_success)
      p_sm_auth_register_role_successOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_sm_auth_register_role_success.newBuilder() to construct.
    private p_sm_auth_register_role_success(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_sm_auth_register_role_success() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_sm_auth_register_role_success(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_register_role_success_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_register_role_success_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success.class, com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success)) {
        return super.equals(obj);
      }
      com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success other = (com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jyg.proto.p_sm_auth_register_role_success}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jyg.proto.p_sm_auth_register_role_success)
        com.jyg.proto.p_auth_sm.p_sm_auth_register_role_successOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_register_role_success_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_register_role_success_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success.class, com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success.Builder.class);
      }

      // Construct using com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_register_role_success_descriptor;
      }

      public com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success getDefaultInstanceForType() {
        return com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success.getDefaultInstance();
      }

      public com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success build() {
        com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success buildPartial() {
        com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success result = new com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success) {
          return mergeFrom((com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success other) {
        if (other == com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jyg.proto.p_sm_auth_register_role_success)
    }

    // @@protoc_insertion_point(class_scope:com.jyg.proto.p_sm_auth_register_role_success)
    private static final com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success();
    }

    public static com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_sm_auth_register_role_success>
        PARSER = new com.google.protobuf.AbstractParser<p_sm_auth_register_role_success>() {
      public p_sm_auth_register_role_success parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new p_sm_auth_register_role_success(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_sm_auth_register_role_success> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_sm_auth_register_role_success> getParserForType() {
      return PARSER;
    }

    public com.jyg.proto.p_auth_sm.p_sm_auth_register_role_success getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface p_auth_sm_request_send_tokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jyg.proto.p_auth_sm_request_send_token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestId = 1;</code>
     */
    long getRequestId();
  }
  /**
   * <pre>
   *auth 给sm服 发送token
   * </pre>
   *
   * Protobuf type {@code com.jyg.proto.p_auth_sm_request_send_token}
   */
  public  static final class p_auth_sm_request_send_token extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jyg.proto.p_auth_sm_request_send_token)
      p_auth_sm_request_send_tokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_auth_sm_request_send_token.newBuilder() to construct.
    private p_auth_sm_request_send_token(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_auth_sm_request_send_token() {
      requestId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_auth_sm_request_send_token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_request_send_token_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_request_send_token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token.class, com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>int64 requestId = 1;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeInt64(1, requestId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token)) {
        return super.equals(obj);
      }
      com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token other = (com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token) obj;

      boolean result = true;
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *auth 给sm服 发送token
     * </pre>
     *
     * Protobuf type {@code com.jyg.proto.p_auth_sm_request_send_token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jyg.proto.p_auth_sm_request_send_token)
        com.jyg.proto.p_auth_sm.p_auth_sm_request_send_tokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_request_send_token_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_request_send_token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token.class, com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token.Builder.class);
      }

      // Construct using com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_auth_sm_request_send_token_descriptor;
      }

      public com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token getDefaultInstanceForType() {
        return com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token.getDefaultInstance();
      }

      public com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token build() {
        com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token buildPartial() {
        com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token result = new com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token(this);
        result.requestId_ = requestId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token) {
          return mergeFrom((com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token other) {
        if (other == com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestId_ ;
      /**
       * <code>int64 requestId = 1;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>int64 requestId = 1;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jyg.proto.p_auth_sm_request_send_token)
    }

    // @@protoc_insertion_point(class_scope:com.jyg.proto.p_auth_sm_request_send_token)
    private static final com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token();
    }

    public static com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_auth_sm_request_send_token>
        PARSER = new com.google.protobuf.AbstractParser<p_auth_sm_request_send_token>() {
      public p_auth_sm_request_send_token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new p_auth_sm_request_send_token(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_auth_sm_request_send_token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_auth_sm_request_send_token> getParserForType() {
      return PARSER;
    }

    public com.jyg.proto.p_auth_sm.p_auth_sm_request_send_token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface p_sm_auth_response_receive_tokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jyg.proto.p_sm_auth_response_receive_token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestId = 1;</code>
     */
    long getRequestId();

    /**
     * <code>string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>string ip = 3;</code>
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 3;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 4;</code>
     */
    int getPort();
  }
  /**
   * <pre>
   *场景服回复sm服
   * </pre>
   *
   * Protobuf type {@code com.jyg.proto.p_sm_auth_response_receive_token}
   */
  public  static final class p_sm_auth_response_receive_token extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jyg.proto.p_sm_auth_response_receive_token)
      p_sm_auth_response_receive_tokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_sm_auth_response_receive_token.newBuilder() to construct.
    private p_sm_auth_response_receive_token(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_sm_auth_response_receive_token() {
      requestId_ = 0L;
      token_ = "";
      ip_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_sm_auth_response_receive_token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 32: {

              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_response_receive_token_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_response_receive_token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token.class, com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>int64 requestId = 1;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 3;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>int32 port = 4;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeInt64(1, requestId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(4, port_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token)) {
        return super.equals(obj);
      }
      com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token other = (com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token) obj;

      boolean result = true;
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && getToken()
          .equals(other.getToken());
      result = result && getIp()
          .equals(other.getIp());
      result = result && (getPort()
          == other.getPort());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *场景服回复sm服
     * </pre>
     *
     * Protobuf type {@code com.jyg.proto.p_sm_auth_response_receive_token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jyg.proto.p_sm_auth_response_receive_token)
        com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_tokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_response_receive_token_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_response_receive_token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token.class, com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token.Builder.class);
      }

      // Construct using com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        token_ = "";

        ip_ = "";

        port_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jyg.proto.p_auth_sm.internal_static_com_jyg_proto_p_sm_auth_response_receive_token_descriptor;
      }

      public com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token getDefaultInstanceForType() {
        return com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token.getDefaultInstance();
      }

      public com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token build() {
        com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token buildPartial() {
        com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token result = new com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token(this);
        result.requestId_ = requestId_;
        result.token_ = token_;
        result.ip_ = ip_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token) {
          return mergeFrom((com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token other) {
        if (other == com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestId_ ;
      /**
       * <code>int64 requestId = 1;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>int64 requestId = 1;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 3;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 4;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 4;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 4;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jyg.proto.p_sm_auth_response_receive_token)
    }

    // @@protoc_insertion_point(class_scope:com.jyg.proto.p_sm_auth_response_receive_token)
    private static final com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token();
    }

    public static com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_sm_auth_response_receive_token>
        PARSER = new com.google.protobuf.AbstractParser<p_sm_auth_response_receive_token>() {
      public p_sm_auth_response_receive_token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new p_sm_auth_response_receive_token(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_sm_auth_response_receive_token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_sm_auth_response_receive_token> getParserForType() {
      return PARSER;
    }

    public com.jyg.proto.p_auth_sm.p_sm_auth_response_receive_token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jyg_proto_p_auth_sm_register_role_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jyg_proto_p_auth_sm_register_role_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jyg_proto_p_sm_auth_register_role_success_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jyg_proto_p_sm_auth_register_role_success_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jyg_proto_p_auth_sm_request_send_token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jyg_proto_p_auth_sm_request_send_token_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jyg_proto_p_sm_auth_response_receive_token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jyg_proto_p_sm_auth_response_receive_token_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017p_auth_sm.proto\022\rcom.jyg.proto\"\031\n\027p_au" +
      "th_sm_register_role\"!\n\037p_sm_auth_registe" +
      "r_role_success\"1\n\034p_auth_sm_request_send" +
      "_token\022\021\n\trequestId\030\001 \001(\003\"^\n p_sm_auth_r" +
      "esponse_receive_token\022\021\n\trequestId\030\001 \001(\003" +
      "\022\r\n\005token\030\002 \001(\t\022\n\n\002ip\030\003 \001(\t\022\014\n\004port\030\004 \001(" +
      "\005B\032\n\rcom.jyg.protoB\tp_auth_smb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jyg_proto_p_auth_sm_register_role_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jyg_proto_p_auth_sm_register_role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jyg_proto_p_auth_sm_register_role_descriptor,
        new java.lang.String[] { });
    internal_static_com_jyg_proto_p_sm_auth_register_role_success_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jyg_proto_p_sm_auth_register_role_success_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jyg_proto_p_sm_auth_register_role_success_descriptor,
        new java.lang.String[] { });
    internal_static_com_jyg_proto_p_auth_sm_request_send_token_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_jyg_proto_p_auth_sm_request_send_token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jyg_proto_p_auth_sm_request_send_token_descriptor,
        new java.lang.String[] { "RequestId", });
    internal_static_com_jyg_proto_p_sm_auth_response_receive_token_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_jyg_proto_p_sm_auth_response_receive_token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jyg_proto_p_sm_auth_response_receive_token_descriptor,
        new java.lang.String[] { "RequestId", "Token", "Ip", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
